### ISSUE TITLE
html网页图片无法显示

### ISSUE THREAD

**Issue by pengbaron** [100askTeam/LinuxDeviceDriver-Tranning#1]
![20240102-111706](https://github.com/100askTeam/LinuxDeviceDriver-Tranning/assets/109021005/14f14cfc-9168-40be-8445-caa9e95db55e)

html网页图片无法显示

**Comment by YobieZhou** [comment]
为什么图片显示不全？因为服务器资源有限，文档图片资料庞大，在购买【百问网韦东山驱动大全课程】之后会有完整的文档资料下载地址，课程获取地址：https://item.taobao.com/item.htm?id=636066114871
